### ISSUE TITLE
(UndefinedFunctionError) function :crypto.hmac/3 is undefined or private, use crypto:mac/4 instead

### ISSUE THREAD

**Issue by metehan** [dashbitco/nimble_totp#28]
Hi I have an issue 
```
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)

iex(noname@83970d7a61ec)2> secret = NimbleTOTP.secret()
<<29, 17, 124, 1, 126, 10, 200, 252, 122, 12>>
iex(noname@83970d7a61ec)3> NimbleTOTP.otpauth_uri("Acme:alice", secret, issuer: "Acme")
"otpauth://totp/Acme:alice?secret=DUIXYAL6BLEPY6QM&issuer=Acme"

iex(noname@83970d7a61ec)4> NimbleTOTP.verification_code(secret)
** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private, use crypto:mac/4 instead
    (crypto 5.1.4.1) :crypto.hmac(:sha, <<29, 17, 124, 1, 126, 10, 200, 252, 122, 12>>, <<0, 0, 0, 0, 3, 96, 14, 114>>)
    (nimble_totp 0.1.0) lib/nimble_totp.ex:139: NimbleTOTP.verification_code/2
    iex:4: (file)

iex(noname@83970d7a61ec)4> NimbleTOTP.valid?(secret, "569777")
** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private, use crypto:mac/4 instead
    (crypto 5.1.4.1) :crypto.hmac(:sha, <<29, 17, 124, 1, 126, 10, 200, 252, 122, 12>>, <<0, 0, 0, 0, 3, 96, 14, 116>>)
    (nimble_totp 0.1.0) lib/nimble_totp.ex:139: NimbleTOTP.verification_code/2
    (nimble_totp 0.1.0) lib/nimble_totp.ex:166: NimbleTOTP.valid?/3
    iex:4: (file)

iex(noname@83970d7a61ec)5>  :crypto.mac(:hmac, :sha, secret, "data")
<<11, 65, 97, 113, 34, 252, 189, 42, 253, 233, 225, 2, 247, 176, 138, 212, 207,
  227, 185, 99>>
iex(spill@83970d7a61ec)6> :crypto.hmac(:sha, key, "data")
** (CompileError) cannot compile code (errors have been logged)

iex(noname@83970d7a61ec)6> function_exported?(:crypto, :mac, 4)
true

iex(noname@83970d7a61ec)7> Code.ensure_loaded?(:crypto)
true
```

https://github.com/dashbitco/nimble_totp/blob/b50480df1f805496d78d19dcfead5f014bc6a00c/lib/nimble_totp.ex#L186
Here it's very clear `Code.ensure_loaded?(:crypto)` and  `function_exported?(:crypto, :mac, 4)` are true so it should never use :crypto.hmac/3 but somehow it happens.

{:nimble_totp, "~> 0.1"},

**Comment by wojtekmach** [comment]
You are using nimble_totp 0.1.0. Please update to the latest version and you should be good to go!
